const T={
es:{title:'📐 Calculador de áreas',desc:'Elige una figura, introduce sus medidas y calcula el área paso a paso.',back:'← Volver',light:'☀️ Claro',dark:'🌙 Oscuro',shape:'Figura',calculate:'📐 Calcular área',loading:'Preparando Python…',ready:'Listo.',value:'⚠️ Escribe medidas positivas válidas.',failed:'⚠️ No se pudo cargar Python. Revisa la conexión y recarga.',area:'Área',note:'Las medidas deben usar la misma unidad. El resultado se expresa en unidades cuadradas.',download:'Descargar código Python',triangulo:'Triángulo',rectangulo:'Rectángulo',cuadrado:'Cuadrado',circulo:'Círculo',trapecio:'Trapecio',paralelogramo:'Paralelogramo',rombo:'Rombo',base:'Base',altura:'Altura',lado:'Lado',radio:'Radio',base_mayor:'Base mayor',base_menor:'Base menor',diagonal_mayor:'Diagonal mayor',diagonal_menor:'Diagonal menor',substitute:'Sustituimos las medidas',result:'Resultado'},
en:{title:'📐 Area calculator',desc:'Choose a shape, enter its measurements and calculate the area step by step.',back:'← Back',light:'☀️ Light',dark:'🌙 Dark',shape:'Shape',calculate:'📐 Calculate area',loading:'Preparing Python…',ready:'Ready.',value:'⚠️ Enter valid positive measurements.',failed:'⚠️ Python could not be loaded. Check your connection and reload.',area:'Area',note:'Use the same unit for all measurements. The result is expressed in square units.',download:'Download Python code',triangulo:'Triangle',rectangulo:'Rectangle',cuadrado:'Square',circulo:'Circle',trapecio:'Trapezoid',paralelogramo:'Parallelogram',rombo:'Rhombus',base:'Base',altura:'Height',lado:'Side',radio:'Radius',base_mayor:'Longer base',base_menor:'Shorter base',diagonal_mayor:'Long diagonal',diagonal_menor:'Short diagonal',substitute:'Substitute the measurements',result:'Result'},
hy:{title:'📐 Մակերեսի հաշվիչ',desc:'Ընտրիր պատկերը, գրիր չափերը և քայլ առ քայլ հաշվիր մակերեսը։',back:'← Հետ',light:'☀️ Բաց',dark:'🌙 Մութ',shape:'Պատկեր',calculate:'📐 Հաշվել մակերեսը',loading:'Python-ը պատրաստվում է…',ready:'Պատրաստ է։',value:'⚠️ Գրիր ճիշտ դրական չափեր։',failed:'⚠️ Python-ը չբեռնվեց։ Ստուգիր կապը և թարմացրու էջը։',area:'Մակերես',note:'Բոլոր չափերի համար օգտագործիր նույն միավորը։ Արդյունքը քառակուսի միավորներով է։',download:'Ներբեռնել Python կոդը',triangulo:'Եռանկյուն',rectangulo:'Ուղղանկյուն',cuadrado:'Քառակուսի',circulo:'Շրջան',trapecio:'Սեղան',paralelogramo:'Զուգահեռագիծ',rombo:'Շեղանկյուն',base:'Հիմք',altura:'Բարձրություն',lado:'Կողմ',radio:'Շառավիղ',base_mayor:'Մեծ հիմք',base_menor:'Փոքր հիմք',diagonal_mayor:'Մեծ անկյունագիծ',diagonal_menor:'Փոքր անկյունագիծ',substitute:'Փոխարինում ենք չափերը',result:'Արդյունք'}
};
const CONFIG={
triangulo:{fields:['base','altura'],formula:'A = (b × h) / 2'},
rectangulo:{fields:['base','altura'],formula:'A = b × h'},
cuadrado:{fields:['lado'],formula:'A = l²'},
circulo:{fields:['radio'],formula:'A = π × r²'},
trapecio:{fields:['base_mayor','base_menor','altura'],formula:'A = ((B + b) × h) / 2'},
paralelogramo:{fields:['base','altura'],formula:'A = b × h'},
rombo:{fields:['diagonal_mayor','diagonal_menor'],formula:'A = (D × d) / 2'}
};
const $=id=>document.getElementById(id);let py=null,state='loading',answer=null;
function lang(){const x=localStorage.getItem('idioma');return T[x]?x:'es'}
function fmt(n){return new Intl.NumberFormat(lang(),{maximumFractionDigits:10,maximumSignificantDigits:12}).format(n)}
function setTheme(){const claro=localStorage.getItem('tema')==='claro';document.body.classList.toggle('claro',claro);$('botonTema').textContent=T[lang()][claro?'dark':'light']}
function buildFields(){const t=T[lang()],cfg=CONFIG[$('figura').value],box=$('campos');box.innerHTML='';cfg.fields.forEach((field,i)=>{const wrap=document.createElement('div'),label=document.createElement('label'),input=document.createElement('input');label.htmlFor='campo_'+field;label.textContent=t[field];input.id='campo_'+field;input.dataset.field=field;input.inputMode='decimal';input.autocomplete='off';input.placeholder=String((i+1)*4);wrap.append(label,input);box.appendChild(wrap);input.addEventListener('input',clearResult)});$('formulaPrevia').textContent=cfg.formula}
function clearResult(){answer=null;$('resultados').classList.add('oculto');if(state==='ready')$('estado').textContent=T[lang()].ready}
function render(){const l=lang(),t=T[l];document.documentElement.lang=l;document.title=t.title.replace(/^📐 /,'')+' - MI WEB';MiWeb.applyLanguage();$('titulo').textContent=t.title;$('descripcion').textContent=t.desc;$('volver').textContent=t.back;$('labelFigura').textContent=t.shape;$('botonCalcular').textContent=t.calculate;$('textoArea').textContent=t.area;$('nota').textContent=t.note;$('descarga').textContent=t.download;[...$('figura').options].forEach(o=>o.textContent=t[o.value]);$('botonIdioma').textContent=l==='en'?'🇬🇧 EN ▾':l==='hy'?'🇦🇲 HY ▾':'🇪🇸 ES ▾';$('botonCalcular').disabled=!py;setTheme();buildFields();if(state==='loading')$('estado').textContent=t.loading;else if(state==='failed')$('estado').textContent=t.failed;else $('estado').textContent=t.ready;if(answer)renderAnswer()}
function renderAnswer(){const t=T[lang()];if(answer.error){$('resultados').classList.add('oculto');$('estado').textContent=t[answer.error]||t.failed;return}$('estado').textContent='';$('resultados').classList.remove('oculto');$('resultadoArea').textContent=fmt(answer.area)+' u²';$('formulaResultado').textContent=answer.formula;const vals=Object.entries(answer.valores).map(([k,v])=>t[k]+' = '+fmt(v)).join(', ');$('pasos').textContent=t.substitute+':\n'+vals+'\n\n'+t.result+': '+fmt(answer.area)+' u²'}
async function init(){state='loading';render();try{if(!window.loadPyodide)await new Promise((ok,no)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/pyodide/v0.27.7/full/pyodide.js';s.onload=ok;s.onerror=no;document.head.appendChild(s)});py=await loadPyodide({indexURL:'https://cdn.jsdelivr.net/pyodide/v0.27.7/full/'});const r=await fetch('calculadora.py');if(!r.ok)throw Error();await py.runPythonAsync(await r.text());state='ready'}catch(e){console.error(e);state='failed'}render()}
$('figura').addEventListener('change',()=>{clearResult();buildFields()});$('formulario').addEventListener('submit',e=>{e.preventDefault();if(!py)return;const vals={};document.querySelectorAll('#campos input').forEach(i=>vals[i.dataset.field]=i.value);const fn=py.globals.get('calcular_json');try{answer=JSON.parse(fn($('figura').value,JSON.stringify(vals)))}catch(e){answer={error:'failed'}}finally{fn.destroy()}if(answer&&!answer.error)MiWeb.updateExtraStats('areas',v=>({...v,calculos:(v.calculos||0)+1}));renderAnswer()});
$('botonIdioma').onclick=()=>{$('menuIdiomas').style.display=$('menuIdiomas').style.display==='block'?'none':'block'};$('menuIdiomas').addEventListener('click',e=>{const b=e.target.closest('[data-lang]');if(!b)return;localStorage.setItem('idioma',b.dataset.lang);$('menuIdiomas').style.display='none';render()});$('botonTema').onclick=()=>{localStorage.setItem('tema',localStorage.getItem('tema')==='claro'?'oscuro':'claro');render()};document.addEventListener('click',e=>{if(!e.target.closest('.menu-idioma'))$('menuIdiomas').style.display='none'});MiWeb.mountRanking({game:'areas',columns:[{key:'calculos',label:{es:'Áreas calculadas',en:'Areas calculated',hy:'Հաշված մակերեսներ'}}],compare:(a,b)=>(b.calculos||0)-(a.calculos||0)});render();init();