const T={
es:{title:'🔗 Conjetura de Collatz',desc:'Escribe un entero positivo y observa su secuencia: si es par se divide entre 2; si es impar se calcula 3n + 1.',back:'← Volver',light:'☀️ Claro',dark:'🌙 Oscuro',placeholder:'Ejemplo: 27',calc:'🔗 Calcular',loading:'Preparando Python…',ready:'Listo. Escribe un número.',invalid:'⚠️ Escribe un número entero positivo.',range:'⚠️ Usa un entero entre 1 y 1.000.000.000.000.000.000.',limit:'⚠️ La secuencia superó el límite de 10.000 pasos.',failed:'⚠️ No se pudo cargar Python. Revisa la conexión y recarga.',steps:'Pasos hasta 1',max:'Valor máximo',peak:'Paso del máximo',graph:'📈 Gráfica',sequence:'🧮 Pasos de la secuencia',step:'Paso',value:'Valor',note:'La conjetura afirma que todo entero positivo acaba llegando a 1, pero todavía no existe una demostración general.',download:'Descargar código Python',linear:'Escala Y lineal',log:'Escala Y logarítmica para que se vean mejor los picos grandes.'},
en:{title:'🔗 Collatz Conjecture',desc:'Enter a positive integer and watch its sequence: divide even numbers by 2; for odd numbers calculate 3n + 1.',back:'← Back',light:'☀️ Light',dark:'🌙 Dark',placeholder:'Example: 27',calc:'🔗 Calculate',loading:'Preparing Python…',ready:'Ready. Enter a number.',invalid:'⚠️ Enter a positive whole number.',range:'⚠️ Use an integer from 1 to 1,000,000,000,000,000,000.',limit:'⚠️ The sequence exceeded the 10,000-step limit.',failed:'⚠️ Python could not be loaded. Check your connection and reload.',steps:'Steps to 1',max:'Maximum value',peak:'Step of maximum',graph:'📈 Graph',sequence:'🧮 Sequence steps',step:'Step',value:'Value',note:'The conjecture says every positive integer eventually reaches 1, but there is still no general proof.',download:'Download Python code',linear:'Linear Y scale',log:'Logarithmic Y scale so large spikes remain visible.'},
hy:{title:'🔗 Կոլացի վարկած',desc:'Գրիր դրական ամբողջ թիվ․ զույգը բաժանվում է 2-ի, իսկ կենտի համար հաշվվում է 3n + 1։',back:'← Հետ',light:'☀️ Բաց',dark:'🌙 Մութ',placeholder:'Օրինակ՝ 27',calc:'🔗 Հաշվել',loading:'Python-ը պատրաստվում է…',ready:'Պատրաստ է։ Գրիր թիվ։',invalid:'⚠️ Գրիր դրական ամբողջ թիվ։',range:'⚠️ Օգտագործիր 1-ից մինչև 1 000 000 000 000 000 000 ամբողջ թիվ։',limit:'⚠️ Հաջորդականությունը անցավ 10 000 քայլի սահմանը։',failed:'⚠️ Python-ը չբեռնվեց։ Ստուգիր կապը և թարմացրու էջը։',steps:'Քայլերը մինչև 1',max:'Առավելագույն արժեք',peak:'Առավելագույնի քայլը',graph:'📈 Գրաֆիկ',sequence:'🧮 Հաջորդականության քայլերը',step:'Քայլ',value:'Արժեք',note:'Վարկածը պնդում է, որ յուրաքանչյուր դրական ամբողջ թիվ վերջում հասնում է 1-ի, բայց ընդհանուր ապացույց դեռ չկա։',download:'Ներբեռնել Python կոդը',linear:'Y առանցքի գծային սանդղակ',log:'Y առանցքի լոգարիթմական սանդղակ՝ մեծ գագաթները լավ տեսնելու համար։'}
};
const $=id=>document.getElementById(id);let py=null,state='loading',data=null;
function lang(){const x=localStorage.getItem('idioma');return T[x]?x:'es'}
function setTheme(){const claro=localStorage.getItem('tema')==='claro';document.body.classList.toggle('claro',claro);$('botonTema').textContent=T[lang()][claro?'dark':'light']}
function renderText(){const l=lang(),t=T[l];document.documentElement.lang=l;document.title=t.title.replace(/^🔗 /,'')+' - MI WEB';MiWeb.applyLanguage();$('titulo').textContent=t.title;$('descripcion').textContent=t.desc;$('volver').textContent=t.back;$('numero').placeholder=t.placeholder;$('botonCalcular').textContent=t.calc;$('labelPasos').textContent=t.steps;$('labelMaximo').textContent=t.max;$('labelPico').textContent=t.peak;$('tituloGrafica').textContent=t.graph;$('tituloSecuencia').textContent=t.sequence;$('thPaso').textContent=t.step;$('thValor').textContent=t.value;$('nota').textContent=t.note;$('descarga').textContent=t.download;$('botonIdioma').textContent=l==='en'?'🇬🇧 EN ▾':l==='hy'?'🇦🇲 HY ▾':'🇪🇸 ES ▾';$('botonCalcular').disabled=!py;$('estado').textContent=state==='loading'?t.loading:state==='failed'?t.failed:state==='ready'&&!data?t.ready:'';setTheme();if(data)renderData()}
function formatBig(s){try{return BigInt(s).toLocaleString(lang())}catch{return s}}
function renderData(){const t=T[lang()];$('resultados').classList.remove('oculto');$('pasos').textContent=data.pasos.toLocaleString(lang());$('maximo').textContent=formatBig(data.maximo);$('pasoMaximo').textContent=data.paso_maximo.toLocaleString(lang());const tbody=$('tablaSecuencia');tbody.innerHTML='';data.secuencia.forEach((v,i)=>{const tr=document.createElement('tr'),a=document.createElement('td'),b=document.createElement('td');a.textContent=i;b.textContent=formatBig(v);tr.append(a,b);tbody.appendChild(tr)});drawGraph();$('estado').textContent=''}
function drawGraph(){if(!data)return;const canvas=$('grafica'),wrap=canvas.parentElement,dpr=Math.min(devicePixelRatio||1,2),w=Math.max(300,wrap.clientWidth),h=330;canvas.width=w*dpr;canvas.height=h*dpr;const c=canvas.getContext('2d');c.scale(dpr,dpr);const vals=data.secuencia.map(Number),max=Math.max(...vals),min=Math.min(...vals),useLog=max/Math.max(min,1)>1000,tx=v=>useLog?Math.log10(v):v;const ys=vals.map(tx),yMin=Math.min(...ys),yMax=Math.max(...ys),pad={l:48,r:15,t:18,b:35};c.clearRect(0,0,w,h);const css=getComputedStyle(document.body),fg=css.color;c.strokeStyle=fg;c.fillStyle=fg;c.globalAlpha=.35;c.lineWidth=1;c.beginPath();c.moveTo(pad.l,pad.t);c.lineTo(pad.l,h-pad.b);c.lineTo(w-pad.r,h-pad.b);c.stroke();c.globalAlpha=1;const x=i=>pad.l+(vals.length===1?0:i/(vals.length-1))*(w-pad.l-pad.r),y=v=>h-pad.b-(v-yMin)/(yMax-yMin||1)*(h-pad.t-pad.b);c.strokeStyle=fg;c.lineWidth=2;c.beginPath();ys.forEach((v,i)=>{const px=x(i),py=y(v);i?c.lineTo(px,py):c.moveTo(px,py)});c.stroke();c.font='12px Arial';c.fillText('0',pad.l-4,h-12);c.fillText(String(vals.length-1),w-pad.r-20,h-12);$('graficaInfo').textContent=T[lang()][useLog?'log':'linear']}
async function init(){state='loading';renderText();try{if(!window.loadPyodide)await new Promise((ok,no)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/pyodide/v0.27.7/full/pyodide.js';s.onload=ok;s.onerror=no;document.head.appendChild(s)});py=await loadPyodide({indexURL:'https://cdn.jsdelivr.net/pyodide/v0.27.7/full/'});const r=await fetch('collatz.py');if(!r.ok)throw Error();await py.runPythonAsync(await r.text());state='ready'}catch(e){console.error(e);state='failed'}renderText()}
$('formulario').addEventListener('submit',e=>{e.preventDefault();if(!py)return;const fn=py.globals.get('collatz_json');let r;try{r=JSON.parse(fn($('numero').value))}catch(e){r={error:'failed'}}finally{fn.destroy()}if(r.error){data=null;$('resultados').classList.add('oculto');$('estado').textContent=T[lang()][r.error]||T[lang()].failed}else{data=r;state='ready';renderData()}});
$('botonIdioma').onclick=()=>{$('menuIdiomas').style.display=$('menuIdiomas').style.display==='block'?'none':'block'};$('menuIdiomas').addEventListener('click',e=>{const b=e.target.closest('[data-lang]');if(!b)return;localStorage.setItem('idioma',b.dataset.lang);$('menuIdiomas').style.display='none';renderText()});$('botonTema').onclick=()=>{localStorage.setItem('tema',localStorage.getItem('tema')==='claro'?'oscuro':'claro');renderText()};document.addEventListener('click',e=>{if(!e.target.closest('.menu-idioma'))$('menuIdiomas').style.display='none'});window.addEventListener('resize',()=>{if(data)drawGraph()});renderText();init();