const T={
es:{title:'⚡ Duelo de cálculo mental',desc:'Resuelve tantas operaciones como puedas en 30 segundos.',back:'← Volver',light:'☀️ Claro',dark:'🌙 Oscuro',difficulty:'Dificultad',easy:'Fácil',medium:'Medio',hard:'Difícil',start:'▶️ Empezar',again:'🔄 Jugar otra vez',time:'Tiempo',points:'Puntos',streak:'Racha',hits:'Aciertos',placeholder:'Respuesta',answer:'✅ Responder',records:'🏆 Tus récords',bestScore:'Mejor puntuación',bestStreak:'Mejor racha',games:'Partidas',note:'Fácil: suma y resta. Medio: añade multiplicaciones. Difícil: incluye divisiones exactas y números mayores.',download:'Descargar código Python',loading:'Preparando juego…',correct:'✅ Correcto',wrong:'❌ Era',invalid:'⚠️ Escribe un número entero.',finish:'⏱️ Tiempo. Puntuación:',ready:'Pulsa Empezar.'},
en:{title:'⚡ Mental math duel',desc:'Solve as many operations as you can in 30 seconds.',back:'← Back',light:'☀️ Light',dark:'🌙 Dark',difficulty:'Difficulty',easy:'Easy',medium:'Medium',hard:'Hard',start:'▶️ Start',again:'🔄 Play again',time:'Time',points:'Points',streak:'Streak',hits:'Correct',placeholder:'Answer',answer:'✅ Answer',records:'🏆 Your records',bestScore:'Best score',bestStreak:'Best streak',games:'Games',note:'Easy: addition and subtraction. Medium: adds multiplication. Hard: includes exact division and larger numbers.',download:'Download Python code',loading:'Preparing game…',correct:'✅ Correct',wrong:'❌ It was',invalid:'⚠️ Enter a whole number.',finish:'⏱️ Time. Score:',ready:'Press Start.'},
hy:{title:'⚡ Մտավոր հաշվարկի մենամարտ',desc:'30 վայրկյանում լուծիր որքան հնարավոր է շատ գործողություններ։',back:'← Հետ',light:'☀️ Բաց',dark:'🌙 Մութ',difficulty:'Դժվարություն',easy:'Հեշտ',medium:'Միջին',hard:'Դժվար',start:'▶️ Սկսել',again:'🔄 Կրկին խաղալ',time:'Ժամանակ',points:'Միավորներ',streak:'Շարք',hits:'Ճիշտ',placeholder:'Պատասխան',answer:'✅ Պատասխանել',records:'🏆 Քո ռեկորդները',bestScore:'Լավագույն միավոր',bestStreak:'Լավագույն շարք',games:'Խաղեր',note:'Հեշտ՝ գումարում և հանում։ Միջին՝ նաև բազմապատկում։ Դժվար՝ ճշգրիտ բաժանում և ավելի մեծ թվեր։',download:'Ներբեռնել Python կոդը',loading:'Խաղը պատրաստվում է…',correct:'✅ Ճիշտ է',wrong:'❌ Պատասխանն էր',invalid:'⚠️ Գրիր ամբողջ թիվ։',finish:'⏱️ Ժամանակը վերջացավ։ Միավորներ՝',ready:'Սեղմիր Սկսել։'}
};
const $=id=>document.getElementById(id);let py=null,op=null,jugando=false,tiempo=30,puntos=0,racha=0,mejorRachaPartida=0,aciertos=0,intervalo=null,finPartidaEn=0;
const STATS='dueloCalculoMentalStatsV1';
function lang(){const x=localStorage.getItem('idioma');return T[x]?x:'es'}
function rnd(a,b){return Math.floor(Math.random()*(b-a+1))+a}
function choice(a){return a[Math.floor(Math.random()*a.length)]}
function nuevaJS(d){let a,b,o,r;if(d==='facil'){o=choice(['+','-']);a=rnd(1,50);b=rnd(1,50);if(o==='-'&&b>a)[a,b]=[b,a];r=o==='+'?a+b:a-b}else if(d==='medio'){o=choice(['+','-','×']);if(o==='×'){a=rnd(2,12);b=rnd(2,12);r=a*b}else{a=rnd(10,150);b=rnd(1,100);if(o==='-'&&b>a)[a,b]=[b,a];r=o==='+'?a+b:a-b}}else{o=choice(['+','-','×','÷']);if(o==='×'){a=rnd(6,25);b=rnd(3,15);r=a*b}else if(o==='÷'){b=rnd(2,15);r=rnd(2,25);a=b*r}else{a=rnd(50,500);b=rnd(10,300);if(o==='-'&&b>a)[a,b]=[b,a];r=o==='+'?a+b:a-b}}return{a,b,operador:o,resultado:r}}
function setTheme(){const claro=localStorage.getItem('tema')==='claro';document.body.classList.toggle('claro',claro);$('botonTema').textContent=T[lang()][claro?'dark':'light']}
function renderText(){const l=lang(),t=T[l];document.documentElement.lang=l;document.title=t.title.replace(/^⚡ /,'')+' - MI WEB';MiWeb.applyLanguage();$('titulo').textContent=t.title;$('descripcion').textContent=t.desc;$('volver').textContent=t.back;$('labelDificultad').textContent=t.difficulty;$('dificultad').options[0].textContent=t.easy;$('dificultad').options[1].textContent=t.medium;$('dificultad').options[2].textContent=t.hard;$('botonInicio').textContent=jugando?t.start:(puntos||aciertos?t.again:t.start);$('textoTiempo').textContent=t.time;$('textoPuntos').textContent=t.points;$('textoRacha').textContent=t.streak;$('textoAciertos').textContent=t.hits;$('respuesta').placeholder=t.placeholder;$('botonComprobar').textContent=t.answer;$('tituloRecords').textContent=t.records;$('textoRecordPuntos').textContent=t.bestScore;$('textoRecordRacha').textContent=t.bestStreak;$('textoPartidas').textContent=t.games;$('nota').textContent=t.note;$('descarga').textContent=t.download;$('botonIdioma').textContent=l==='en'?'🇬🇧 EN ▾':l==='hy'?'🇦🇲 HY ▾':'🇪🇸 ES ▾';setTheme()}
function stats(){let all={};try{all=JSON.parse(localStorage.getItem(STATS)||'{}')}catch{}const id=MiWeb.profile().id;return {all,id,value:all[id]&&typeof all[id]==='object'?all[id]:{mejorPuntuacion:0,mejorRacha:0,partidas:0}}}
function mostrarStats(){const s=stats().value;$('recordPuntos').textContent=s.mejorPuntuacion||0;$('recordRacha').textContent=s.mejorRacha||0;$('recordPartidas').textContent=s.partidas||0}
function guardarStats(){const s=stats();s.value.mejorPuntuacion=Math.max(s.value.mejorPuntuacion||0,puntos);s.value.mejorRacha=Math.max(s.value.mejorRacha||0,mejorRachaPartida);s.value.partidas=(s.value.partidas||0)+1;s.all[s.id]=s.value;localStorage.setItem(STATS,JSON.stringify(s.all));MiWeb.updateExtraStats('duelo-calculo',v=>({...v,mejorPuntuacion:Math.max(v.mejorPuntuacion||0,puntos),mejorRacha:Math.max(v.mejorRacha||0,mejorRachaPartida),partidas:(v.partidas||0)+1}));mostrarStats()}
async function cargarOperacion(){const d=$('dificultad').value;if(py){const fn=py.globals.get('nueva_json');try{op=JSON.parse(fn(d))}catch(e){console.warn(e);op=nuevaJS(d)}finally{fn.destroy()}}else op=nuevaJS(d);$('operacion').textContent=op.a+' '+op.operador+' '+op.b+' = ?';$('respuesta').value='';$('respuesta').focus()}
function actualizar(){$('tiempo').textContent=tiempo;$('puntos').textContent=puntos;$('racha').textContent=racha;$('aciertos').textContent=aciertos}
async function iniciar(){if(jugando)return;jugando=true;tiempo=30;puntos=0;racha=0;mejorRachaPartida=0;aciertos=0;$('mensaje').textContent='';$('dificultad').disabled=true;$('respuesta').disabled=false;$('botonComprobar').disabled=false;$('botonInicio').disabled=true;actualizar();await cargarOperacion();finPartidaEn=Date.now()+30000;intervalo=setInterval(()=>{tiempo=Math.max(0,Math.ceil((finPartidaEn-Date.now())/1000));actualizar();if(tiempo===0)terminar()},250)}
function terminar(){if(!jugando)return;jugando=false;clearInterval(intervalo);intervalo=null;$('respuesta').disabled=true;$('botonComprobar').disabled=true;$('dificultad').disabled=false;$('botonInicio').disabled=false;$('operacion').textContent='—';$('mensaje').textContent=T[lang()].finish+' '+puntos;guardarStats();MiWeb.xpAction('game_finish');renderText()}
$('formulario').addEventListener('submit',async e=>{e.preventDefault();if(!jugando||!op)return;const texto=$('respuesta').value.trim(),n=Number(texto);if(!texto||!Number.isInteger(n)){$('mensaje').textContent=T[lang()].invalid;return}let correcto=n===op.resultado;if(py){const fn=py.globals.get('comprobar_json');try{const r=JSON.parse(fn(String(op.resultado),texto));if(!r.error)correcto=r.correcto}catch(e){console.warn(e)}finally{fn.destroy()}}if(correcto){puntos++;aciertos++;racha++;mejorRachaPartida=Math.max(mejorRachaPartida,racha);$('mensaje').textContent=T[lang()].correct;MiWeb.xpAction('correct')}else{$('mensaje').textContent=T[lang()].wrong+' '+op.resultado;racha=0;MiWeb.xpAction('wrong')}actualizar();await cargarOperacion()});
async function initPython(){try{if(!window.loadPyodide)await new Promise((ok,no)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/pyodide/v0.27.7/full/pyodide.js';s.onload=ok;s.onerror=no;document.head.appendChild(s)});py=await window.loadPyodide({indexURL:'https://cdn.jsdelivr.net/pyodide/v0.27.7/full/'});const r=await fetch('calculo.py',{cache:'no-store'});if(!r.ok)throw Error();await py.runPythonAsync(await r.text())}catch(e){console.warn('Modo compatible sin Pyodide',e);py=null}}
$('botonInicio').addEventListener('click',iniciar);$('botonIdioma').onclick=()=>{$('menuIdiomas').style.display=$('menuIdiomas').style.display==='block'?'none':'block'};$('menuIdiomas').addEventListener('click',e=>{const b=e.target.closest('[data-lang]');if(!b)return;localStorage.setItem('idioma',b.dataset.lang);$('menuIdiomas').style.display='none';renderText()});$('botonTema').onclick=()=>{localStorage.setItem('tema',localStorage.getItem('tema')==='claro'?'oscuro':'claro');renderText()};document.addEventListener('click',e=>{if(!e.target.closest('.menu-idioma'))$('menuIdiomas').style.display='none'});const previo=stats();const extra=MiWeb.readExtraStats('duelo-calculo');if(!extra[previo.id]&&(previo.value.partidas||0)>0)MiWeb.updateExtraStats('duelo-calculo',()=>({...previo.value}));MiWeb.mountRanking({game:'duelo-calculo',columns:[{key:'mejorPuntuacion',label:{es:'Mejor puntuación',en:'Best score',hy:'Լավագույն միավոր'}},{key:'mejorRacha',label:{es:'Mejor racha',en:'Best streak',hy:'Լավագույն շարք'}},{key:'partidas',label:{es:'Partidas',en:'Games',hy:'Խաղեր'}}],compare:(a,b)=>(b.mejorPuntuacion||0)-(a.mejorPuntuacion||0)||(b.mejorRacha||0)-(a.mejorRacha||0)||(b.partidas||0)-(a.partidas||0)});renderText();mostrarStats();actualizar();$('mensaje').textContent=T[lang()].ready;initPython();