const T={
es:{title:'📊 Calculadora de porcentajes',desc:'Calcula una subida o bajada desde el valor inicial, o descubre el valor inicial conociendo el resultado final.',back:'← Volver',light:'☀️ Claro',dark:'🌙 Oscuro',mode:'¿Qué conoces?',initial:'Valor inicial',final:'Valor final',type:'¿Qué ocurrió?',up:'Subida',down:'Bajada',percent:'Porcentaje',calc:'📊 Calcular',loading:'Preparando Python…',ready:'Listo.',value:'⚠️ Escribe un valor válido entre 0 y 1.000.000.000.000.000.',percentErr:'⚠️ Escribe un porcentaje válido.',decrease100:'⚠️ Una bajada no puede superar el 100%.',reverse100:'⚠️ No se puede recuperar el valor inicial después de una bajada exacta del 100%.',failed:'⚠️ No se pudo cargar Python. Revisa la conexión y recarga.',change:'Cambio',note:'Ejemplo: si 100 sube un 20%, pasa a 120. Si sabes que el final es 120 después de subir un 20%, el inicial era 100.',download:'Descargar código Python',fromInitial:'Partimos del valor inicial',fromFinal:'Partimos del valor final',multiply:'Multiplicamos por',divide:'Dividimos entre'},
en:{title:'📊 Percentage calculator',desc:'Calculate an increase or decrease from the starting value, or recover the starting value from the final result.',back:'← Back',light:'☀️ Light',dark:'🌙 Dark',mode:'What do you know?',initial:'Starting value',final:'Final value',type:'What happened?',up:'Increase',down:'Decrease',percent:'Percentage',calc:'📊 Calculate',loading:'Preparing Python…',ready:'Ready.',value:'⚠️ Enter a valid value from 0 to 1,000,000,000,000,000.',percentErr:'⚠️ Enter a valid percentage.',decrease100:'⚠️ A decrease cannot exceed 100%.',reverse100:'⚠️ The starting value cannot be recovered after an exact 100% decrease.',failed:'⚠️ Python could not be loaded. Check your connection and reload.',change:'Change',note:'Example: if 100 increases by 20%, it becomes 120. If the final value is 120 after a 20% increase, the starting value was 100.',download:'Download Python code',fromInitial:'Start from the initial value',fromFinal:'Start from the final value',multiply:'Multiply by',divide:'Divide by'},
hy:{title:'📊 Տոկոսների հաշվիչ',desc:'Հաշվիր սկզբնական արժեքից աճը կամ նվազումը, կամ վերջնական արժեքից գտիր սկզբնականը։',back:'← Հետ',light:'☀️ Բաց',dark:'🌙 Մութ',mode:'Ի՞նչն է հայտնի',initial:'Սկզբնական արժեք',final:'Վերջնական արժեք',type:'Ի՞նչ է տեղի ունեցել',up:'Աճ',down:'Նվազում',percent:'Տոկոս',calc:'📊 Հաշվել',loading:'Python-ը պատրաստվում է…',ready:'Պատրաստ է։',value:'⚠️ Գրիր ճիշտ արժեք՝ 0-ից մինչև 1 000 000 000 000 000։',percentErr:'⚠️ Գրիր ճիշտ տոկոս։',decrease100:'⚠️ Նվազումը չի կարող գերազանցել 100%-ը։',reverse100:'⚠️ Ճիշտ 100% նվազումից հետո սկզբնական արժեքը հնարավոր չէ վերականգնել։',failed:'⚠️ Python-ը չբեռնվեց։ Ստուգիր կապը և թարմացրու էջը։',change:'Փոփոխություն',note:'Օրինակ՝ եթե 100-ը աճում է 20%-ով, դառնում է 120։ Եթե վերջնականը 120 է 20% աճից հետո, սկզբնականը 100 էր։',download:'Ներբեռնել Python կոդը',fromInitial:'Սկսում ենք սկզբնական արժեքից',fromFinal:'Սկսում ենք վերջնական արժեքից',multiply:'Բազմապատկում ենք',divide:'Բաժանում ենք'}
};
const $=id=>document.getElementById(id);let py=null,state='loading',answer=null;
function lang(){const x=localStorage.getItem('idioma');return T[x]?x:'es'}
function fmt(n){return new Intl.NumberFormat(lang(),{maximumFractionDigits:10,maximumSignificantDigits:12}).format(n)}
function setTheme(){const claro=localStorage.getItem('tema')==='claro';document.body.classList.toggle('claro',claro);$('botonTema').textContent=T[lang()][claro?'dark':'light']}
function updateValueLabel(){const t=T[lang()],fromInitial=$('modo').value==='desde_inicial';$('labelValor').textContent=fromInitial?t.initial:t.final;$('valor').placeholder=fromInitial?'100':'120'}
function render(){const l=lang(),t=T[l];document.documentElement.lang=l;document.title=t.title.replace(/^📊 /,'')+' - MI WEB';MiWeb.applyLanguage();$('titulo').textContent=t.title;$('descripcion').textContent=t.desc;$('volver').textContent=t.back;$('labelModo').textContent=t.mode;$('labelTipo').textContent=t.type;$('labelPorcentaje').textContent=t.percent;$('botonCalcular').textContent=t.calc;$('textoInicial').textContent=t.initial;$('textoFinal').textContent=t.final;$('textoCambio').textContent=t.change;$('nota').textContent=t.note;$('descarga').textContent=t.download;$('modo').options[0].textContent=t.initial;$('modo').options[1].textContent=t.final;$('tipo').options[0].textContent=t.up;$('tipo').options[1].textContent=t.down;$('botonIdioma').textContent=l==='en'?'🇬🇧 EN ▾':l==='hy'?'🇦🇲 HY ▾':'🇪🇸 ES ▾';$('botonCalcular').disabled=!py;updateValueLabel();setTheme();if(state==='loading')$('estado').textContent=t.loading;else if(state==='failed')$('estado').textContent=t.failed;else if(!answer)$('estado').textContent=t.ready;if(answer)renderAnswer()}
function renderAnswer(){const t=T[lang()];if(answer.error){$('resultados').classList.add('oculto');$('estado').textContent=t[answer.error]||t.failed;return}$('estado').textContent='';$('resultados').classList.remove('oculto');$('resultadoInicial').textContent=fmt(answer.inicial);$('resultadoFinal').textContent=fmt(answer.final);const sign=answer.diferencia>0?'+':'';$('resultadoCambio').textContent=sign+fmt(answer.diferencia)+' ('+sign+fmt(answer.porcentaje_real)+'%)';const factor=fmt(answer.factor),p=fmt(answer.porcentaje);if(answer.modo==='desde_inicial'){$('pasos').textContent=`${t.fromInitial}: ${fmt(answer.inicial)}\n${answer.tipo==='subida'?t.up:t.down}: ${p}%\n${t.multiply}: ${factor}\n${fmt(answer.inicial)} × ${factor} = ${fmt(answer.final)}`}else{$('pasos').textContent=`${t.fromFinal}: ${fmt(answer.final)}\n${answer.tipo==='subida'?t.up:t.down}: ${p}%\n${t.divide}: ${factor}\n${fmt(answer.final)} ÷ ${factor} = ${fmt(answer.inicial)}`}}
async function init(){state='loading';render();try{if(!window.loadPyodide)await new Promise((ok,no)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/pyodide/v0.27.7/full/pyodide.js';s.onload=ok;s.onerror=no;document.head.appendChild(s)});py=await loadPyodide({indexURL:'https://cdn.jsdelivr.net/pyodide/v0.27.7/full/'});const r=await fetch('calculadora.py');if(!r.ok)throw Error();await py.runPythonAsync(await r.text());state='ready'}catch(e){console.error(e);state='failed'}render()}
$('formulario').addEventListener('submit',e=>{e.preventDefault();if(!py)return;const fn=py.globals.get('calcular_json');try{answer=JSON.parse(fn($('modo').value,$('tipo').value,$('valor').value,$('porcentaje').value))}catch(e){answer={error:'failed'}}finally{fn.destroy()}renderAnswer();MiWeb.xpAction(answer&&answer.error?'tool_invalid':'tool_success')});
['modo','tipo','valor','porcentaje'].forEach(id=>$(id).addEventListener(id==='modo'||id==='tipo'?'change':'input',()=>{answer=null;$('resultados').classList.add('oculto');$('estado').textContent=state==='ready'?T[lang()].ready:'';updateValueLabel()}));
$('botonIdioma').onclick=()=>{$('menuIdiomas').style.display=$('menuIdiomas').style.display==='block'?'none':'block'};$('menuIdiomas').addEventListener('click',e=>{const b=e.target.closest('[data-lang]');if(!b)return;localStorage.setItem('idioma',b.dataset.lang);$('menuIdiomas').style.display='none';render()});$('botonTema').onclick=()=>{localStorage.setItem('tema',localStorage.getItem('tema')==='claro'?'oscuro':'claro');render()};document.addEventListener('click',e=>{if(!e.target.closest('.menu-idioma'))$('menuIdiomas').style.display='none'});render();init();