const $=id=>document.getElementById(id),KEY='miWebDurakV1';
const T={
es:{levels:['Principiante','Medio','Difícil','Imposible'],difficulty:'Dificultad',new:'Nueva partida',desc:'Quédate sin cartas antes que el bot. Imposible usa simulaciones sin ver tu mano: es el nivel más fuerte, pero se puede ganar.',round:'Ronda',stock:'Mazo',discard:'Descartadas',trump:'Triunfo',bot:'Bot',you:'Tú',cards:'cartas',attack:'Tu turno: ataca con una carta.',add:'Puedes añadir cartas del mismo valor que alguna de la mesa o terminar.',defend:'Defiende la carta marcada o recoge.',taking:'El bot recoge. Puedes añadir cartas antes de terminar.',thinking:'El bot está pensando…',win:'¡Has ganado! El bot es el Durak.',lose:'Gana el bot. ¡Prueba otra partida!',draw:'Empate: ambos os habéis quedado sin cartas.',take:'Recoger',end:'Terminar ataque',hand:'Tu mano',hint:'Las cartas resaltadas son legales. Para defender, pulsa primero el ataque que quieres cubrir y después una carta de tu mano.',rulesTitle:'Cómo jugar',rules:'36 cartas, del 6 al as. Cada jugador recibe 6. Empieza quien tenga el triunfo más bajo; si nadie tiene triunfos, se sortea. Se defiende con una carta superior del mismo palo o un triunfo; un triunfo solo se supera con otro mayor. Solo puedes añadir valores presentes en la mesa. Máximo 6 ataques y nunca más cartas que las que tenía el defensor al comenzar la ronda. Al recoger se lleva toda la mesa, incluidas las defensas. El atacante aún puede añadir cartas. Roba primero el atacante y después el defensor hasta tener 6; el triunfo visible se roba al final. Si defiendes, atacas; si recoges, vuelve a atacar el rival. El resultado se decide al terminar la ronda y agotar el mazo.',history:'Historial',saved:'La partida se guarda en este navegador y continúa al volver. Cambiar la dificultad empieza una partida nueva.',confirm:'¿Abandonar esta partida y empezar otra?',attackLog:'ataca',defendLog:'defiende',takeLog:'recoge',endLog:'termina el ataque',starter:'Empieza',limit:'Límite',none:'Sin cartas en la mesa'},
en:{levels:['Beginner','Medium','Hard','Impossible'],difficulty:'Difficulty',new:'New game',desc:'Run out of cards before the bot. Impossible uses simulations without seeing your hand: strongest, but beatable.',round:'Round',stock:'Deck',discard:'Discarded',trump:'Trump',bot:'Bot',you:'You',cards:'cards',attack:'Your turn: play an attack.',add:'Add a matching rank or finish the attack.',defend:'Cover the selected attack or take the cards.',taking:'The bot is taking. You can add cards before finishing.',thinking:'Bot is thinking…',win:'You win! The bot is the Durak.',lose:'The bot wins. Try another game!',draw:'Draw: both players ran out of cards.',take:'Take cards',end:'Finish attack',hand:'Your hand',hint:'Highlighted cards are legal. To defend, select an attack first, then a card from your hand.',rulesTitle:'How to play',rules:'36 cards, 6 through ace. Six cards per player. Lowest trump starts; random starter if neither has trumps. Cover with a higher card of the same suit or a trump. A trump needs a higher trump. Added attacks must match a rank on the table. At most six attacks, limited by the defender’s starting hand size. Taking collects the entire table, including defenses; the attacker may add more first. Attacker draws to six, then defender; the face-up trump is drawn last. After a successful defense, roles swap; after taking, the attacker attacks again. Results are checked at round end once the deck is empty.',history:'Move history',saved:'Your game is saved in this browser. Changing difficulty starts a new game.',confirm:'Leave this game and start a new one?',attackLog:'attacks',defendLog:'defends',takeLog:'takes',endLog:'finishes the attack',starter:'Starts',limit:'Limit',none:'No cards on the table'},
hy:{levels:['Սկսնակ','Միջին','Դժվար','Անհնար'],difficulty:'Բարդություն',new:'Նոր խաղ',desc:'Ազատվիր քարտերից բոտից առաջ։ Անհնար մակարդակը հաշվարկում է տարբերակներ՝ առանց քո քարտերը տեսնելու։ Հաղթել հնարավոր է։',round:'Փուլ',stock:'Կապուկ',discard:'Դուրս եկած',trump:'Կոզիր',bot:'Բոտ',you:'Դու',cards:'քարտ',attack:'Քո հերթն է․ հարձակվիր։',add:'Ավելացրու սեղանին եղած արժեքով քարտ կամ ավարտիր։',defend:'Պաշտպանիր նշված քարտը կամ վերցրու։',taking:'Բոտը վերցնում է։ Կարող ես քարտեր ավելացնել։',thinking:'Բոտը մտածում է…',win:'Դու հաղթեցիր։ Բոտը դուրակն է։',lose:'Բոտը հաղթեց։ Փորձիր նորից։',draw:'Ոչ-ոքի․ երկուսի քարտերն էլ վերջացան։',take:'Վերցնել',end:'Ավարտել հարձակումը',hand:'Քո քարտերը',hint:'Նշված քարտերով կարելի է խաղալ։ Պաշտպանվելու համար նախ ընտրիր հարձակման քարտը, հետո քո քարտը։',rulesTitle:'Ինչպես խաղալ',rules:'36 քարտ՝ 6-ից մինչև տուզ։ Յուրաքանչյուրին՝ 6 քարտ։ Սկսում է ամենափոքր կոզիր ունեցողը։ Եթե կոզիր չկա, սկսողը պատահական է։ Պաշտպանիր նույն տեսակի բարձր քարտով կամ կոզիրով։ Կոզիրը հաղթում է միայն բարձր կոզիրը։ Ավելացվող քարտի արժեքը պետք է լինի սեղանին։ Առավելագույնը 6 հարձակում՝ ոչ ավելի, քան պաշտպանի սկզբնական քարտերի քանակը։ Վերցնելիս վերցնում ես ամբողջ սեղանը։ Հարձակվողը դեռ կարող է ավելացնել։ Նախ հարձակվողը, ապա պաշտպանը լրացնում են մինչև 6 քարտ։ Բաց կոզիրը վերցվում է վերջինը։ Հաջող պաշտպանությունից հետո դերերը փոխվում են, վերցնելուց հետո՝ ոչ։ Արդյունքը որոշվում է փուլի ավարտին, երբ կապուկը դատարկ է։',history:'Քայլերի պատմություն',saved:'Խաղը պահվում է այս դիտարկիչում։ Բարդությունը փոխելիս նոր խաղ է սկսվում։',confirm:'Ավարտե՞լ այս խաղը և սկսել նորը։',attackLog:'հարձակվում է',defendLog:'պաշտպանում է',takeLog:'վերցնում է',endLog:'ավարտում է հարձակումը',starter:'Սկսում է',limit:'Սահման',none:'Սեղանը դատարկ է'}
};
let lang=localStorage.getItem('idioma')||'es';if(!T[lang])lang='es';let state,level=1,history=[],selected=0,timer,serial=0;
const suits=['♠','♥','♦','♣'],rank=c=>({11:'J',12:'Q',13:'K',14:'A'}[c.r]||c.r),name=c=>rank(c)+suits[c.s];
function valid(s){if(!s||!Array.isArray(s.hands)||s.hands.length!==2||!Array.isArray(s.deck)||!Array.isArray(s.discard)||!Array.isArray(s.table))return false;const all=[...s.hands.flat(),...s.deck,...s.discard,...s.table.flatMap(p=>[p.a,...(p.d?[p.d]:[])])];return all.length===36&&new Set(all.map(c=>c.id)).size===36&&all.every(c=>c.id===c.s*9+c.r-6&&c.r>=6&&c.r<=14&&c.s>=0&&c.s<=3)&&[0,1].includes(s.turn)&&[0,1].includes(s.attacker)&&[null,0,1,2].includes(s.winner)&&Number.isInteger(s.limit)&&s.limit>=0&&s.limit<=6}
try{const v=JSON.parse(localStorage.getItem(KEY));if(v&&valid(v.state)&&[0,1,2,3].includes(v.level)){state=v.state;level=v.level;history=Array.isArray(v.history)?v.history:[]}}catch{}
if(!state)state=Durak.create();
function save(){try{localStorage.setItem(KEY,JSON.stringify({state,level,history}))}catch{}}
function card(c,click){const b=document.createElement(click?'button':'div');b.className='card'+([1,2].includes(c.s)?' red':'');b.setAttribute('aria-label',name(c));const r=document.createElement('span'),s=document.createElement('span');r.textContent=name(c);s.textContent=suits[c.s];s.className='suit';b.append(r,s);if(click)b.onclick=click;return b}
function play(m){const actor=state.turn,c=state.hands[actor].find(c=>c.id===m.id);history.push({actor,type:m.type,card:c?name(c):'',round:state.round});history=history.slice(-160);Durak.apply(state,m);selected=state.table.findIndex(p=>!p.d);save();render();schedule()}
function render(){const t=T[lang];document.documentElement.lang=lang;document.body.classList.toggle('claro',localStorage.getItem('tema')==='claro');$('language').value=lang;$('level').value=level;[...$('level').options].forEach((o,i)=>o.textContent=t.levels[i]);$('levelLabel').textContent=t.difficulty;$('new').textContent=t.new;$('description').textContent=t.desc;$('round').textContent=t.round+' '+state.round;$('stock').textContent=t.stock+': '+state.deck.length;$('discard').textContent=t.discard+': '+state.discard.length;$('trump').textContent=t.trump+': '+suits[state.trump]+(state.deck.length?' · '+name(state.face):'');$('opponent').textContent=t.bot+' · '+t.levels[level]+' · '+state.hands[1].length+' '+t.cards;$('backs').replaceChildren();for(let i=0;i<Math.min(12,state.hands[1].length);i++){const b=document.createElement('div');b.className='back';$('backs').append(b)}
const moves=Durak.actions(state),human=state.turn===0&&state.winner===null;
if(!state.table[selected]||state.table[selected].d)selected=state.table.findIndex(p=>!p.d);
$('status').textContent=state.winner!==null?(state.winner===0?t.win:state.winner===1?t.lose:t.draw):!human?t.thinking:state.attacker===0?(state.taking?t.taking:state.table.length?t.add:t.attack):t.defend;
$('table').replaceChildren();if(!state.table.length)$('table').textContent=t.none;
state.table.forEach((p,i)=>{const pair=document.createElement('div');pair.className='pair'+(human&&state.attacker===1&&!p.d&&i===selected?' selected':'');const a=card(p.a,human&&state.attacker===1&&!p.d?()=>{selected=i;render()}:null);pair.append(a);if(p.d){const d=card(p.d);d.classList.add('defense');pair.append(d)}$('table').append(pair)});
$('hand').replaceChildren();[...state.hands[0]].sort((a,b)=>(a.s===state.trump)-(b.s===state.trump)||a.s-b.s||a.r-b.r).forEach(c=>{const m=moves.find(m=>m.id===c.id&&(m.type!=='defend'||m.index===selected));const b=card(c,()=>{if(human&&m)play(m)});b.disabled=!human||!m;if(human&&m)b.classList.add('legal');$('hand').append(b)});
$('take').textContent=t.take;$('end').textContent=t.end;$('take').disabled=!human||!moves.some(m=>m.type==='take');$('end').disabled=!human||!moves.some(m=>m.type==='end');$('handLabel').textContent=t.hand+' · '+state.hands[0].length+' '+t.cards;$('hint').textContent=level===0?t.hint:state.winner!==null?'':t.limit+': '+state.table.length+'/'+state.limit;$('rulesTitle').textContent=t.rulesTitle;$('rules').textContent=t.rules;$('historyTitle').textContent=t.history;$('saveNote').textContent=t.saved;
$('history').replaceChildren();for(const e of history){const li=document.createElement('li');li.textContent=t.round+' '+e.round+' · '+(e.actor===0?t.you:t.bot)+' '+t[e.type+'Log']+' '+e.card;$('history').append(li)} }
function schedule(){clearTimeout(timer);if(state.turn!==1||state.winner!==null)return;const token=serial;timer=setTimeout(()=>{if(token!==serial)return;play(Durak.choose(state,level))},500)}
function restart(next){if(state.winner===null&&history.length&&!confirm(T[lang].confirm)){$('level').value=level;return}serial++;clearTimeout(timer);level=next;state=Durak.create();history=[];selected=0;save();render();schedule()}
$('new').onclick=()=>restart(level);$('level').onchange=()=>restart(Number($('level').value));$('take').onclick=()=>play({type:'take'});$('end').onclick=()=>play({type:'end'});$('theme').onclick=()=>{localStorage.setItem('tema',localStorage.getItem('tema')==='claro'?'oscuro':'claro');render()};$('language').onchange=()=>{lang=$('language').value;localStorage.setItem('idioma',lang);render()};save();render();schedule();
