/* Podkidnoy, two players. Pure rules shared by UI, AI and tests. */
(function(root){
const deck=()=>Array.from({length:36},(_,id)=>({id,s:Math.floor(id/9),r:id%9+6}));
function shuffle(a,rng=Math.random){for(let i=a.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function create(){const d=shuffle(deck()),h=[d.splice(0,6),d.splice(0,6)],trump=d[0].s;const lowest=h.map(x=>Math.min(...x.filter(c=>c.s===trump).map(c=>c.r)));const a=lowest[0]===lowest[1]?Math.floor(Math.random()*2):lowest[0]<lowest[1]?0:1;return {hands:h,deck:d,trump,face:d[0],table:[],discard:[],attacker:a,turn:a,limit:6,taking:false,round:1,winner:null}}
const beats=(c,a,t)=>(c.s===a.s&&c.r>a.r)||(c.s===t&&a.s!==t);
function actions(s){if(s.winner!==null)return [];const h=s.hands[s.turn];if(s.turn===s.attacker){const ranks=s.table.flatMap(p=>[p.a.r,...(p.d?[p.d.r]:[])]);const moves=s.table.length<s.limit?h.filter(c=>!s.table.length||ranks.includes(c.r)).map(c=>({type:'attack',id:c.id})):[];if(s.table.length&&(s.taking||s.table.every(p=>p.d)))moves.push({type:'end'});return moves}return [...h.flatMap(c=>s.table.flatMap((p,i)=>!p.d&&beats(c,p.a,s.trump)?[{type:'defend',id:c.id,index:i}]:[])),{type:'take'}]}
function finish(s){const a=s.attacker,d=1-a;const cards=s.table.flatMap(p=>[p.a,...(p.d?[p.d]:[])]);if(s.taking)s.hands[d].push(...cards);else s.discard.push(...cards);for(const p of [a,d])while(s.hands[p].length<6&&s.deck.length)s.hands[p].push(s.deck.pop());const next=s.taking?a:d;s.table=[];s.taking=false;s.round++;if(!s.deck.length){const empty=s.hands.map(h=>!h.length);if(empty[0]||empty[1])s.winner=empty[0]&&empty[1]?2:empty[0]?0:1} s.attacker=next;s.turn=next;s.limit=Math.min(6,s.hands[1-next].length)}
function apply(s,m){if(!actions(s).some(x=>JSON.stringify(x)===JSON.stringify(m)))throw Error('Illegal move');if(m.type==='end'){finish(s);return s}if(m.type==='take'){s.taking=true;s.turn=s.attacker;return s}const h=s.hands[s.turn],i=h.findIndex(c=>c.id===m.id),c=h.splice(i,1)[0];if(m.type==='attack'){s.table.push({a:c,d:null});if(!s.taking)s.turn=1-s.attacker}else{s.table[m.index].d=c;if(s.table.every(p=>p.d))s.turn=s.attacker}return s}
const value=(c,s)=>c.r+(c.s===s.trump?15:0);
function heuristic(s,level=2){const moves=actions(s);if(level===0)return moves[Math.floor(Math.random()*moves.length)];const h=s.hands[s.turn];const scored=moves.map(m=>{const c=h.find(c=>c.id===m.id);let v=0;if(m.type==='attack'){v=30-value(c,s)+(level>1?h.filter(x=>x.r===c.r).length*3:0);if(s.taking&&c.s===s.trump&&s.deck.length)v-=25}if(m.type==='defend'){v=35-value(c,s);if(level>1){const ranks=new Set(s.table.flatMap(p=>[p.a.r,p.d?.r]));if(ranks.has(c.r))v+=4}}if(m.type==='take')v=s.deck.length&&level>1?3:-30;if(m.type==='end')v=0;return {m,v}});scored.sort((a,b)=>b.v-a.v);return scored[0].m}
/* Impossible samples only unseen cards. It never reads the real opponent hand/order. */
function choose(s,level){if(level<3)return heuristic(s,level);const moves=actions(s);if(moves.length===1)return moves[0];const p=s.turn;const known=[...s.hands[p],...s.discard,...s.table.flatMap(x=>[x.a,...(x.d?[x.d]:[])])];if(s.deck.length)known.push(s.face);const ids=new Set(known.map(c=>c.id));const unknown=deck().filter(c=>!ids.has(c.id));const totals=moves.map(()=>0);const samples=Math.max(8,Math.floor(160/moves.length));for(let k=0;k<samples;k++){const pool=shuffle(unknown.slice());const hands=[[],[]];hands[p]=s.hands[p];hands[1-p]=pool.splice(0,s.hands[1-p].length);const d=s.deck.length?[s.face,...pool]:[];for(let j=0;j<moves.length;j++){const sim=JSON.parse(JSON.stringify({...s,hands,deck:d}));apply(sim,moves[j]);for(let n=0;n<100&&sim.winner===null;n++)apply(sim,heuristic(sim,2));totals[j]+=sim.winner===p?100:sim.winner===1-p?-100:sim.winner===2?0:(sim.hands[1-p].length-sim.hands[p].length)*3+sim.hands[p].reduce((a,c)=>a+value(c,sim),0)*.1}}return moves[totals.indexOf(Math.max(...totals))]}
const api={deck,create,actions,apply,beats,choose,shuffle};if(typeof module!=='undefined')module.exports=api;else root.Durak=api;
})(typeof window!=='undefined'?window:globalThis);
