const T={
es:{title:'🧪 Criba de Eratóstenes',desc:'Observa cómo se eliminan los múltiplos hasta quedar solo los números primos.',back:'← Volver',light:'☀️ Claro',dark:'🌙 Oscuro',limit:'Hasta qué número',create:'Crear',step:'Siguiente paso',auto:'▶️ Automático',stop:'⏸️ Parar',base:'◉ Número que estamos usando',removed:'✕ Múltiplo eliminado',prime:'✓ Primo final',summary:'📊 Resumen del experimento',primes:'Primos encontrados',explorations:'Exploraciones',max:'Mayor límite probado',note:'La criba empieza por 2 y va tachando sus múltiplos; después repite con el siguiente número que todavía no ha sido eliminado.',ready:'Pulsa “Siguiente paso” para comenzar.',using:'Eliminando múltiplos de',done:'Terminado. Los números sin tachar son primos.',range:'Usa un número entre 10 y 2000.'},
en:{title:'🧪 Sieve of Eratosthenes',desc:'Watch multiples disappear until only prime numbers remain.',back:'← Back',light:'☀️ Light',dark:'🌙 Dark',limit:'Up to which number',create:'Create',step:'Next step',auto:'▶️ Automatic',stop:'⏸️ Stop',base:'◉ Number currently used',removed:'✕ Removed multiple',prime:'✓ Final prime',summary:'📊 Experiment summary',primes:'Primes found',explorations:'Explorations',max:'Highest limit tried',note:'The sieve starts with 2 and crosses out its multiples, then repeats with the next number that has not been removed.',ready:'Press “Next step” to begin.',using:'Removing multiples of',done:'Finished. The numbers not crossed out are prime.',range:'Use a number from 10 to 2000.'},
hy:{title:'🧪 Էրատոսթենեսի մաղ',desc:'Դիտիր, թե ինչպես են բազմապատիկները հեռացվում և մնում միայն պարզ թվերը։',back:'← Հետ',light:'☀️ Բաց',dark:'🌙 Մութ',limit:'Մինչև որ թիվը',create:'Ստեղծել',step:'Հաջորդ քայլ',auto:'▶️ Ավտոմատ',stop:'⏸️ Կանգ',base:'◉ Օգտագործվող թիվը',removed:'✕ Հեռացված բազմապատիկ',prime:'✓ Վերջնական պարզ թիվ',summary:'📊 Փորձի ամփոփում',primes:'Գտնված պարզ թվեր',explorations:'Փորձարկումներ',max:'Ամենամեծ սահմանը',note:'Մաղը սկսում է 2-ից և հեռացնում դրա բազմապատիկները, հետո անցնում է հաջորդ չհեռացված թվին։',ready:'Սեղմիր «Հաջորդ քայլ»՝ սկսելու համար։',using:'Հեռացվում են բազմապատիկները՝',done:'Ավարտված է։ Չհեռացված թվերը պարզ են։',range:'Օգտագործիր 10-ից 2000 թիվ։'}
};
const $=id=>document.getElementById(id);let limit=2000,removed=new Set(),bases=[],stepIndex=0,timer=null,completed=false;
function lang(){const x=localStorage.getItem('idioma');return T[x]?x:'es'}
function setTheme(){const claro=localStorage.getItem('tema')==='claro';document.body.classList.toggle('claro',claro);$('botonTema').textContent=T[lang()][claro?'dark':'light']}
function renderText(){const t=T[lang()],l=lang();document.documentElement.lang=l;document.title=t.title.replace(/^🧪 /,'')+' - MI WEB';MiWeb.applyLanguage();$('titulo').textContent=t.title;$('descripcion').textContent=t.desc;$('volver').textContent=t.back;$('labelLimite').textContent=t.limit;$('botonCrear').textContent=t.create;$('botonPaso').textContent=t.step;$('botonAuto').textContent=timer?t.stop:t.auto;$('leyendaBase').textContent=t.base;$('leyendaEliminado').textContent=t.removed;$('leyendaPrimo').textContent=t.prime;$('tituloResumen').textContent=t.summary;$('textoPrimos').textContent=t.primes;$('nota').textContent=t.note;$('botonIdioma').textContent=l==='en'?'🇬🇧 EN ▾':l==='hy'?'🇦🇲 HY ▾':'🇪🇸 ES ▾';setTheme()}
function primeList(n){const mark=Array(n+1).fill(true);mark[0]=mark[1]=false;for(let p=2;p*p<=n;p++)if(mark[p])for(let m=p*p;m<=n;m+=p)mark[m]=false;return mark.map((v,i)=>v?i:null).filter(v=>v!==null)}
function build(track=false){if(timer)stopAuto();const n=Number($('limite').value);if(!Number.isInteger(n)||n<10||n>2000){$('estado').textContent=T[lang()].range;if(track)MiWeb.xpAction('experiment_invalid');return}limit=n;removed=new Set();bases=[];for(let p=2;p*p<=limit;p++){let prime=true;for(let d=2;d*d<=p;d++)if(p%d===0){prime=false;break}if(prime)bases.push(p)}stepIndex=0;completed=false;draw();$('estado').textContent=T[lang()].ready;$('botonPaso').disabled=false;$('cantidadPrimos').textContent=primeList(limit).length;if(track)MiWeb.xpAction('experiment_run')}
function draw(){const grid=$('grid');grid.innerHTML='';for(let n=1;n<=limit;n++){const el=document.createElement('div');el.className='n';el.textContent=n;if(n===1||removed.has(n))el.classList.add('eliminado');if(!completed&&bases[stepIndex]===n)el.classList.add('base');if(completed&&n>1&&!removed.has(n))el.classList.add('primo');grid.appendChild(el)}}
function next(){if(completed)return;if(stepIndex>=bases.length){completed=true;draw();$('estado').textContent=T[lang()].done;$('botonPaso').disabled=true;if(timer)stopAuto();return}const p=bases[stepIndex];for(let m=p*p;m<=limit;m+=p)removed.add(m);$('estado').textContent=T[lang()].using+' '+p;stepIndex++;if(stepIndex>=bases.length){completed=true;draw();$('estado').textContent=T[lang()].done;$('botonPaso').disabled=true;if(timer)stopAuto()}else draw()}
function stopAuto(){clearInterval(timer);timer=null;$('botonAuto').textContent=T[lang()].auto}
function toggleAuto(){if(timer){stopAuto();return}if(completed)build();timer=setInterval(next,700);$('botonAuto').textContent=T[lang()].stop}
$('botonCrear').addEventListener('click',()=>build(true));$('botonPaso').addEventListener('click',next);$('botonAuto').addEventListener('click',toggleAuto);$('botonIdioma').onclick=()=>{$('menuIdiomas').style.display=$('menuIdiomas').style.display==='block'?'none':'block'};$('menuIdiomas').addEventListener('click',e=>{const b=e.target.closest('[data-lang]');if(!b)return;localStorage.setItem('idioma',b.dataset.lang);$('menuIdiomas').style.display='none';renderText()});$('botonTema').onclick=()=>{localStorage.setItem('tema',localStorage.getItem('tema')==='claro'?'oscuro':'claro');renderText()};document.addEventListener('click',e=>{if(!e.target.closest('.menu-idioma'))$('menuIdiomas').style.display='none'});
renderText();build();