const T={
es:{title:'🎯 Disparador de primos',desc:'Dispara solo a los números primos antes de que lleguen abajo.',back:'← Volver',light:'☀️ Claro',dark:'🌙 Oscuro',points:'Puntos',streak:'Racha',lives:'Vidas',level:'Nivel',ready:'¿Preparado?',startText:'Haz clic o toca únicamente los números primos.',start:'▶️ Empezar',again:'🔄 Jugar otra vez',note:'Si disparas a un número compuesto o dejas escapar un primo, pierdes una vida. Los compuestos pueden caer sin problema.',records:'🏆 Tus récords',bestScore:'Mejor puntuación',bestStreak:'Mejor racha',games:'Partidas',prime:'✅ Primo',composite:'❌ Compuesto',escaped:'⚠️ Se escapó un primo',over:'Fin de la partida · Puntos:'},
en:{title:'🎯 Prime shooter',desc:'Shoot only the prime numbers before they reach the bottom.',back:'← Back',light:'☀️ Light',dark:'🌙 Dark',points:'Points',streak:'Streak',lives:'Lives',level:'Level',ready:'Ready?',startText:'Click or tap only the prime numbers.',start:'▶️ Start',again:'🔄 Play again',note:'If you shoot a composite number or let a prime escape, you lose a life. Composite numbers may fall safely.',records:'🏆 Your records',bestScore:'Best score',bestStreak:'Best streak',games:'Games',prime:'✅ Prime',composite:'❌ Composite',escaped:'⚠️ A prime escaped',over:'Game over · Score:'},
hy:{title:'🎯 Պարզ թվերի հրաձիգ',desc:'Կրակիր միայն պարզ թվերին՝ մինչև դրանք հասնեն ներքև։',back:'← Հետ',light:'☀️ Բաց',dark:'🌙 Մութ',points:'Միավորներ',streak:'Շարք',lives:'Կյանքեր',level:'Մակարդակ',ready:'Պատրա՞ստ ես',startText:'Սեղմիր միայն պարզ թվերի վրա։',start:'▶️ Սկսել',again:'🔄 Կրկին խաղալ',note:'Եթե կրակում ես բաղադրյալ թվի վրա կամ պարզ թիվը հասնում է ներքև, կորցնում ես կյանք։',records:'🏆 Քո ռեկորդները',bestScore:'Լավագույն միավոր',bestStreak:'Լավագույն շարք',games:'Խաղեր',prime:'✅ Պարզ թիվ',composite:'❌ Բաղադրյալ թիվ',escaped:'⚠️ Պարզ թիվը փախավ',over:'Խաղն ավարտվեց · Միավորներ՝'}
};
const $=id=>document.getElementById(id),canvas=$('juego'),ctx=canvas.getContext('2d');
let targets=[],playing=false,last=0,spawnTimer=0,score=0,streak=0,bestRunStreak=0,lives=3,level=1,raf=0;
function lang(){const x=localStorage.getItem('idioma');return T[x]?x:'es'}
function isPrime(n){if(n<2)return false;if(n%2===0)return n===2;for(let d=3;d*d<=n;d+=2)if(n%d===0)return false;return true}
function rand(a,b){return Math.floor(Math.random()*(b-a+1))+a}
function setTheme(){const claro=localStorage.getItem('tema')==='claro';document.body.classList.toggle('claro',claro);$('botonTema').textContent=T[lang()][claro?'dark':'light'];draw()}
function renderText(){const t=T[lang()],l=lang();document.documentElement.lang=l;document.title=t.title.replace(/^🎯 /,'')+' - MI WEB';MiWeb.applyLanguage();$('titulo').textContent=t.title;$('descripcion').textContent=t.desc;$('volver').textContent=t.back;$('textoPuntos').textContent=t.points;$('textoRacha').textContent=t.streak;$('textoVidas').textContent=t.lives;$('textoNivel').textContent=t.level;$('overlayTitulo').textContent=playing?'':t.ready;$('overlayTexto').textContent=t.startText;$('botonInicio').textContent=score>0?t.again:t.start;$('nota').textContent=t.note;$('tituloRecords').textContent=t.records;$('textoMejorPuntuacion').textContent=t.bestScore;$('textoMejorRacha').textContent=t.bestStreak;$('textoPartidas').textContent=t.games;$('botonIdioma').textContent=l==='en'?'🇬🇧 EN ▾':l==='hy'?'🇦🇲 HY ▾':'🇪🇸 ES ▾';setTheme();showStats();MiWeb.refreshRanking('disparador-primos')}
function stats(){const d=MiWeb.readExtraStats('disparador-primos'),id=MiWeb.profile().id;return d[id]||{mejorPuntuacion:0,mejorRacha:0,partidas:0}}
function showStats(){const s=stats();$('mejorPuntuacion').textContent=s.mejorPuntuacion||0;$('mejorRacha').textContent=s.mejorRacha||0;$('partidas').textContent=s.partidas||0}
function updateHud(){$('puntos').textContent=score;$('racha').textContent=streak;$('vidas').textContent=lives;$('nivel').textContent=level}
function spawn(){const n=rand(2,99),r=26,x=rand(r+5,canvas.width-r-5),speed=55+level*12+Math.random()*25;targets.push({n,x,y:-r,r,speed,prime:isPrime(n)})}
function draw(){const css=getComputedStyle(document.body),fg=css.color,bg=document.body.classList.contains('claro')?'#fafafa':'#101010';ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle=bg;ctx.fillRect(0,0,canvas.width,canvas.height);ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='bold 20px Arial';for(const t of targets){ctx.beginPath();ctx.arc(t.x,t.y,t.r,0,Math.PI*2);ctx.fillStyle=document.body.classList.contains('claro')?'#e9e9e9':'#262626';ctx.fill();ctx.strokeStyle=fg;ctx.globalAlpha=.5;ctx.stroke();ctx.globalAlpha=1;ctx.fillStyle=fg;ctx.fillText(String(t.n),t.x,t.y)}}
function endGame(){if(!playing)return;playing=false;cancelAnimationFrame(raf);MiWeb.updateExtraStats('disparador-primos',v=>({...v,mejorPuntuacion:Math.max(v.mejorPuntuacion||0,score),mejorRacha:Math.max(v.mejorRacha||0,bestRunStreak),partidas:(v.partidas||0)+1}));showStats();$('mensaje').textContent=T[lang()].over+' '+score;$('overlay').classList.remove('oculto');$('overlayTitulo').textContent=T[lang()].over+' '+score;$('botonInicio').textContent=T[lang()].again;MiWeb.refreshRanking('disparador-primos')}
function loseLife(message){lives--;streak=0;$('mensaje').textContent=message;updateHud();if(lives<=0)endGame()}
function tick(ts){if(!playing)return;if(!last)last=ts;const dt=Math.min((ts-last)/1000,.05);last=ts;spawnTimer-=dt;level=1+Math.floor(score/8);if(spawnTimer<=0){spawn();spawnTimer=Math.max(.38,1.05-level*.07)}for(const t of targets)t.y+=t.speed*dt;const escaped=[];targets=targets.filter(t=>{if(t.y-t.r>canvas.height){if(t.prime)escaped.push(t);return false}return true});if(escaped.length)loseLife(T[lang()].escaped);draw();if(playing)raf=requestAnimationFrame(tick)}
function start(){targets=[];playing=true;last=0;spawnTimer=.25;score=0;streak=0;bestRunStreak=0;lives=3;level=1;$('mensaje').textContent='';$('overlay').classList.add('oculto');updateHud();raf=requestAnimationFrame(tick)}
function pointer(e){if(!playing)return;const rect=canvas.getBoundingClientRect(),x=(e.clientX-rect.left)*canvas.width/rect.width,y=(e.clientY-rect.top)*canvas.height/rect.height;for(let i=targets.length-1;i>=0;i--){const t=targets[i];if((x-t.x)**2+(y-t.y)**2<=t.r**2){targets.splice(i,1);if(t.prime){score++;streak++;bestRunStreak=Math.max(bestRunStreak,streak);$('mensaje').textContent=T[lang()].prime}else loseLife(T[lang()].composite);updateHud();draw();break}}}
canvas.addEventListener('pointerdown',pointer);$('botonInicio').addEventListener('click',start);$('botonIdioma').onclick=()=>{$('menuIdiomas').style.display=$('menuIdiomas').style.display==='block'?'none':'block'};$('menuIdiomas').addEventListener('click',e=>{const b=e.target.closest('[data-lang]');if(!b)return;localStorage.setItem('idioma',b.dataset.lang);$('menuIdiomas').style.display='none';renderText()});$('botonTema').onclick=()=>{localStorage.setItem('tema',localStorage.getItem('tema')==='claro'?'oscuro':'claro');renderText()};document.addEventListener('click',e=>{if(!e.target.closest('.menu-idioma'))$('menuIdiomas').style.display='none'});
MiWeb.mountRanking({game:'disparador-primos',columns:[{key:'mejorPuntuacion',label:{es:'Mejor puntuación',en:'Best score',hy:'Լավագույն միավոր'}},{key:'mejorRacha',label:{es:'Mejor racha',en:'Best streak',hy:'Լավագույն շարք'}},{key:'partidas',label:{es:'Partidas',en:'Games',hy:'Խաղեր'}}],compare:(a,b)=>(b.mejorPuntuacion||0)-(a.mejorPuntuacion||0)||(b.mejorRacha||0)-(a.mejorRacha||0)});renderText();updateHud();draw();